// packages/web-chat-view/src/default-composer.tsx
import { markdown } from "@codemirror/lang-markdown";
import { languages } from "@codemirror/language-data";
import { EditorView } from "@codemirror/view";
import CodeMirror from "@uiw/react-codemirror";
import { LoaderCircle, SendHorizontal } from "lucide-react";
import { useCallback, useMemo, useState } from "react";

import type { WebChatComposerRenderProps } from "./types";

export const DefaultWebChatComposer = ({
  channel,
  disabled,
  sending,
  connectionState,
  onSubmit,
}: WebChatComposerRenderProps) => {
  const [draft, setDraft] = useState("");
  const canSubmit = !disabled && !sending && draft.trim().length > 0;

  const handleSubmit = useCallback(async () => {
    const text = draft.trim();
    if (!canSubmit || text.length === 0) {
      return;
    }
    await onSubmit({ text, assets: [] });
    setDraft("");
  }, [canSubmit, draft, onSubmit]);

  const extensions = useMemo(
    () => [
      markdown({ codeLanguages: languages }),
      EditorView.lineWrapping,
      EditorView.domEventHandlers({
        keydown: (event) => {
          if (event.key !== "Enter" || event.shiftKey || event.metaKey || event.ctrlKey || event.altKey || event.isComposing) {
            return false;
          }
          event.preventDefault();
          void handleSubmit();
          return true;
        },
      }),
      EditorView.theme({
        "&": { fontSize: "13px", backgroundColor: "transparent" },
        ".cm-scroller": { fontFamily: "var(--font-sans)", lineHeight: "1.5" },
        ".cm-content": { padding: "10px 12px", minHeight: "72px" },
        ".cm-gutters": { display: "none" },
        ".cm-focused": { outline: "none" },
        ".cm-editor": { backgroundColor: "transparent" },
        ".cm-placeholder": { color: "#94a3b8" },
        ".cm-cursor": { borderLeftColor: "#0f766e" },
      }),
    ],
    [handleSubmit],
  );

  return (
    <section className="border-t border-slate-200 bg-white/94 px-2 py-2 backdrop-blur md:px-2.5 md:py-2.5">
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs">
        <CodeMirror
          value={draft}
          extensions={extensions}
          editable={!disabled && !sending}
          placeholder={`Message ${channel.title}...`}
          onChange={setDraft}
          basicSetup={{
            lineNumbers: false,
            foldGutter: false,
            highlightActiveLine: false,
            highlightActiveLineGutter: false,
          }}
        />
        <div className="flex items-center justify-between gap-3 border-t border-slate-200 px-3 py-2 text-[11px] text-slate-500">
          <span>{connectionState === "connected" ? "Enter to send, Shift+Enter for newline" : "Waiting for channel transport"}</span>
          <button
            type="button"
            disabled={!canSubmit}
            onClick={() => {
              void handleSubmit();
            }}
            className="inline-flex items-center gap-1 rounded-full bg-slate-900 px-3 py-1.5 text-[11px] font-medium text-white transition disabled:cursor-not-allowed disabled:bg-slate-300"
          >
            {sending ? <LoaderCircle className="h-3.5 w-3.5 animate-spin" /> : <SendHorizontal className="h-3.5 w-3.5" />}
            <span>Send</span>
          </button>
        </div>
      </div>
    </section>
  );
};

// packages/web-chat-view/src/default-composer.svelte
<script lang="ts">
  import type { WebChatComposerRenderProps } from "./types";

  let {
    channel,
    disabled,
    sending,
    connectionState,
    hintText,
    onSubmit,
  }: WebChatComposerRenderProps = $props();

  let draft = $state("");

  const canSubmit = $derived(!disabled && !sending && draft.trim().length > 0);

  const submit = async (): Promise<void> => {
    const text = draft.trim();
    if (!canSubmit || text.length === 0) {
      return;
    }
    await onSubmit({ text, assets: [] });
    draft = "";
  };

  const handleKeydown = (event: KeyboardEvent): void => {
    if (
      event.key !== "Enter" ||
      event.shiftKey ||
      event.metaKey ||
      event.ctrlKey ||
      event.altKey ||
      event.isComposing
    ) {
      return;
    }
    event.preventDefault();
    void submit();
  };
</script>

<section class="composer" part="composer">
  <div class="composer-frame" part="composer-frame">
    <textarea
      class="composer-textarea"
      part="composer-textarea"
      bind:value={draft}
      rows="4"
      disabled={disabled || sending}
      placeholder={`Message ${channel.title}...`}
      onkeydown={handleKeydown}
    ></textarea>
    <div class="composer-footer" part="composer-footer">
      <span part="composer-hint" aria-live="polite">{hintText}</span>
      <button
        type="button"
        class="composer-send"
        part="composer-send"
        disabled={!canSubmit}
        onclick={() => void submit()}
      >
        {sending ? "Sending..." : "Send"}
      </button>
    </div>
  </div>
</section>

<style>
  .composer {
    border-top: 1px solid var(--web-chat-border, #dbe1ea);
    background: var(--web-chat-surface, rgba(255, 255, 255, 0.94));
    padding: 0.75rem;
  }

  .composer[part~="composer"] {
    container-type: inline-size;
  }

  .composer-frame {
    overflow: hidden;
    border: 1px solid var(--web-chat-border, #dbe1ea);
    border-radius: 1.125rem;
    background: #fff;
    box-shadow: 0 8px 24px rgba(15, 23, 42, 0.04);
  }

  .composer-textarea {
    width: 100%;
    min-height: 5rem;
    resize: vertical;
    border: 0;
    background: transparent;
    padding: 0.85rem 1rem;
    font: inherit;
    font-size: 0.95rem;
    line-height: 1.55;
    color: var(--web-chat-foreground, #0f172a);
    outline: none;
  }

  .composer-textarea::placeholder {
    color: #94a3b8;
  }

  .composer-textarea:disabled {
    cursor: not-allowed;
    opacity: 0.7;
  }

  .composer-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.75rem;
    border-top: 1px solid var(--web-chat-border, #dbe1ea);
    padding: 0.75rem 1rem;
    font-size: 0.75rem;
    color: #64748b;
  }

  .composer-send {
    border: 0;
    border-radius: 999px;
    background: #0f172a;
    padding: 0.45rem 0.9rem;
    color: #fff;
    font: inherit;
    font-size: 0.78rem;
    font-weight: 600;
    cursor: pointer;
    transition: opacity 120ms ease;
  }

  .composer-send:disabled {
    cursor: not-allowed;
    opacity: 0.45;
  }

  @container (max-width: 34rem) {
    .composer-footer {
      align-items: stretch;
      flex-direction: column;
    }

    .composer-send {
      width: 100%;
    }
  }
</style>
