// packages/web-chat-view/src/composer/composer-action-bar.svelte
<script lang="ts">
  import ImagePlus from "@lucide/svelte/icons/image-plus";
  import LoaderCircle from "@lucide/svelte/icons/loader-circle";
  import MonitorUp from "@lucide/svelte/icons/monitor-up";
  import Paperclip from "@lucide/svelte/icons/paperclip";
  import SendHorizontal from "@lucide/svelte/icons/send-horizontal";

  import { Button } from "../ui/button";
  import type { ResolvedWebChatComposerCapabilities } from "./composer-contract";

  let {
    disabled,
    submitting,
    canSubmit,
    capabilities,
    onAttach,
    onCaptureScreenshot,
    onSubmit,
  }: {
    disabled: boolean;
    submitting: boolean;
    canSubmit: boolean;
    capabilities: ResolvedWebChatComposerCapabilities;
    onAttach: () => void;
    onCaptureScreenshot: () => void;
    onSubmit: () => void;
  } = $props();
</script>

<div class="composer-actions" data-composer-row="actions" part="composer-actions">
  <div class="composer-actions-leading">
    <Button
      type="button"
      size="sm"
      variant="outline"
      class="composer-action-chip"
      disabled={disabled || submitting}
      title="Attach files"
      hidden={!capabilities.attachmentEnabled}
      aria-hidden={!capabilities.attachmentEnabled}
      onclick={onAttach}
    >
      <span class:hidden={!capabilities.imageEnabled}>
        <ImagePlus class="size-4" />
      </span>
      <span class:hidden={capabilities.imageEnabled}>
        <Paperclip class="size-4" />
      </span>
      <span class="composer-action-label">Attach</span>
    </Button>

    <Button
      type="button"
      size="sm"
      variant="outline"
      class="composer-action-chip"
      disabled={disabled || submitting}
      title="Capture screenshot"
      hidden={!capabilities.screenshotEnabled}
      aria-hidden={!capabilities.screenshotEnabled}
      onclick={onCaptureScreenshot}
    >
      <MonitorUp class="size-4" />
      <span class="composer-action-label">Screenshot</span>
    </Button>
  </div>

  <Button
    type="button"
    size="sm"
    class="composer-send"
    disabled={!canSubmit}
    title={capabilities.submitTitle ?? capabilities.submitLabel}
    part="composer-send"
    onclick={onSubmit}
  >
    <span class:hidden={!submitting}>
      <LoaderCircle class="size-4 animate-spin" />
    </span>
    <span class:hidden={submitting}>
      <SendHorizontal class="size-4" />
    </span>
    <span class="composer-send-label">{capabilities.submitLabel}</span>
  </Button>
</div>

<style>
  .composer-actions {
    display: grid;
    grid-template-columns: minmax(0, 1fr) auto;
    align-items: center;
    gap: 0.5rem;
  }

  .composer-actions-leading {
    display: flex;
    min-width: 0;
    flex-wrap: wrap;
    gap: 0.375rem;
  }

  :global(.composer-action-chip) {
    min-width: 0;
    border-radius: 0.8rem;
    box-shadow: none;
  }

  :global(.composer-send) {
    min-width: 5.25rem;
    border-radius: 0.82rem;
    padding-inline: 0.85rem;
    box-shadow: none;
  }

  @container (max-width: 34rem) {
    .composer-action-label {
      display: none;
    }

    :global(.composer-action-chip) {
      width: 2rem;
      min-width: 2rem;
      padding-inline: 0;
      border-radius: 0.72rem;
    }

    :global(.composer-send) {
      min-width: 4.8rem;
      padding-inline: 0.72rem;
    }
  }

  @container (max-width: 22rem) {
    :global(.composer-send) {
      min-width: 2rem;
      padding-inline: 0.6rem;
    }

    .composer-send-label {
      display: none;
    }
  }
</style>

// packages/webui/src/features/chat/ComposerActionBar.tsx
import { ImagePlus, LoaderCircle, MonitorUp, Paperclip, SendHorizontal } from "lucide-react";
import { useLayoutEffect, useRef, useState, type RefObject } from "react";

import { AdaptiveIconButton } from "../../components/ui/adaptive-icon-button";
import { Button, ButtonLabel, ButtonLeadingVisual } from "../../components/ui/button";

interface ComposerActionBarProps {
  disabled: boolean;
  submitting: boolean;
  canSubmit: boolean;
  imageEnabled: boolean;
  screenshotSupported: boolean;
  submitLabel: string;
  submitTitle?: string;
  fileInputRef: RefObject<HTMLInputElement | null>;
  onFileInputChange: (files: FileList | null) => void;
  onCaptureScreenshot: () => void;
  onSubmit: () => void;
}

export const ComposerActionBar = ({
  disabled,
  submitting,
  canSubmit,
  imageEnabled,
  screenshotSupported,
  submitLabel,
  submitTitle,
  fileInputRef,
  onFileInputChange,
  onCaptureScreenshot,
  onSubmit,
}: ComposerActionBarProps) => {
  const leadingGroupRef = useRef<HTMLDivElement | null>(null);
  const [collapseSecondaryLabels, setCollapseSecondaryLabels] = useState(false);

  useLayoutEffect(() => {
    const container = leadingGroupRef.current;
    if (!container || typeof ResizeObserver === "undefined") {
      return;
    }

    const update = () => {
      const collapseThreshold = imageEnabled && screenshotSupported ? 188 : 96;
      setCollapseSecondaryLabels(container.clientWidth < collapseThreshold);
    };

    update();
    const observer = new ResizeObserver(update);
    observer.observe(container);
    return () => {
      observer.disconnect();
    };
  }, [imageEnabled, screenshotSupported]);

  return (
    <div
      className="grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-center gap-2 px-1.5 py-1.5 md:px-2"
      data-testid="composer-action-bar"
      data-composer-row="actions"
    >
      <input
        ref={fileInputRef}
        type="file"
        accept="image/*,video/*,*/*"
        multiple
        className="hidden"
        onChange={(event) => {
          onFileInputChange(event.target.files);
          event.currentTarget.value = "";
        }}
      />

      <div
        ref={leadingGroupRef}
        className="flex min-w-0 items-center justify-start gap-1.5"
        data-testid="composer-action-leading"
      >
        <AdaptiveIconButton
          type="button"
          size="sm"
          variant="outline"
          disabled={disabled || submitting}
          icon={imageEnabled ? ImagePlus : Paperclip}
          label="Attach"
          tooltip="Attach files, videos, or supported images"
          labelPriority={collapseSecondaryLabels ? "icon-only" : "always"}
          onClick={() => fileInputRef.current?.click()}
          containerClassName="min-w-0 shrink-0"
        />

        {imageEnabled && screenshotSupported ? (
          <AdaptiveIconButton
            type="button"
            size="sm"
            variant="outline"
            disabled={disabled || submitting}
            icon={MonitorUp}
            label="Screenshot"
            tooltip="Capture a screenshot and add it as an attachment"
            labelPriority={collapseSecondaryLabels ? "icon-only" : "always"}
            onClick={onCaptureScreenshot}
            containerClassName="min-w-0 shrink-0"
          />
        ) : null}
      </div>

      <Button
        type="button"
        disabled={!canSubmit}
        onClick={onSubmit}
        title={submitTitle ?? submitLabel}
        className="shrink-0 justify-self-end"
        data-testid="composer-action-primary"
      >
        <ButtonLeadingVisual>
          {submitting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <SendHorizontal className="h-4 w-4" />}
        </ButtonLeadingVisual>
        <ButtonLabel>{submitLabel}</ButtonLabel>
      </Button>
    </div>
  );
};
