// extensions/studio/src/lib/components/ui/password-input.svelte
<script lang="ts">
	import EyeIcon from '@lucide/svelte/icons/eye';
	import EyeOffIcon from '@lucide/svelte/icons/eye-off';
	import type { HTMLInputAttributes } from 'svelte/elements';

	import { Button } from '$lib/components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { cn } from '$lib/utils.js';

	type PasswordInputProps = Omit<HTMLInputAttributes, 'type' | 'value' | 'files'> & {
		value?: string;
		class?: string;
		inputClass?: string;
		toggleLabel?: string;
	};

	let {
		value = $bindable(''),
		class: className = '',
		inputClass = '',
		disabled = false,
		toggleLabel = 'Toggle password visibility',
		...restProps
	}: PasswordInputProps = $props();

	let revealed = $state(false);
</script>

<div class={cn('relative min-w-0', className)}>
	<Input
		bind:value
		type={revealed ? 'text' : 'password'}
		{disabled}
		class={cn('pr-11', inputClass)}
		{...restProps}
	/>
	<Button
		type="button"
		variant="ghost"
		size="icon-sm"
		class="absolute right-1 top-1/2 -translate-y-1/2"
		{disabled}
		aria-label={revealed ? 'Hide password' : 'Show password'}
		title={toggleLabel}
		onclick={() => {
			revealed = !revealed;
		}}
	>
		{#if revealed}
			<EyeOffIcon class="size-4" />
		{:else}
			<EyeIcon class="size-4" />
		{/if}
	</Button>
</div>

// packages/webui-bak/src/components/ui/password-input.tsx
import { Eye, EyeOff } from "lucide-react";
import * as React from "react";

import { cn } from "../../lib/utils";
import { Button } from "./button";
import { Input, type InputProps } from "./input";

export interface PasswordInputProps extends InputProps {
  toggleLabel?: {
    show: string;
    hide: string;
  };
}

export const PasswordInput = React.forwardRef<HTMLInputElement, PasswordInputProps>(
  ({ className, toggleLabel, type: _type, ...props }, ref) => {
    const [revealed, setRevealed] = React.useState(false);
    const labels = toggleLabel ?? { show: "Show value", hide: "Hide value" };

    return (
      <div className={cn("relative flex items-center", className)}>
        <Input ref={ref} {...props} type={revealed ? "text" : "password"} className="pr-11" />
        <Button
          type="button"
          size="icon"
          variant="ghost"
          className="absolute inset-y-0 right-0 my-auto mr-1 h-7 w-7"
          aria-label={revealed ? labels.hide : labels.show}
          title={revealed ? labels.hide : labels.show}
          onClick={() => setRevealed((current) => !current)}
        >
          {revealed ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
        </Button>
      </div>
    );
  },
);
PasswordInput.displayName = "PasswordInput";
