// packages/webui/src/features/chat/ComposerStatusBar.tsx
import { ImagePlus, LoaderCircle, TextCursorInput } from "lucide-react";
import { useMemo } from "react";

import { HelpHint } from "../../components/ui/help-hint";
import { Tooltip } from "../../components/ui/tooltip";
import { cn } from "../../lib/utils";

interface ComposerStatusBarProps {
  disabled: boolean;
  submitting: boolean;
  imageEnabled: boolean;
  screenshotSupported: boolean;
}

const ShortcutHint = ({ label, value }: { label: string; value: string }) => (
  <span className="inline-flex h-5 items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-1.5 text-[10px] leading-none text-slate-600">
    <kbd className="rounded bg-white px-1 py-0.5 font-mono text-[9px] font-medium text-slate-500 ring-1 ring-slate-200">
      {label}
    </kbd>
    <span>{value}</span>
  </span>
);

const COMPOSER_HELP_ITEMS: Array<{ label: string; value: string }> = [
  { label: "@", value: "path" },
  { label: "/", value: "command" },
  { label: "Enter", value: "send" },
  { label: "Shift+Enter", value: "newline" },
  { label: "Drop", value: "files" },
  { label: "Paste", value: "image" },
];

const statusMeta = (input: {
  disabled: boolean;
  submitting: boolean;
  imageEnabled: boolean;
  screenshotSupported: boolean;
}): {
  label: string;
  toneClassName: string;
  iconClassName: string;
  Icon: typeof TextCursorInput;
} => {
  if (input.submitting) {
    return {
      label: "Sending",
      toneClassName: "border-amber-200 bg-amber-50 text-amber-800",
      iconClassName: "animate-spin",
      Icon: LoaderCircle,
    };
  }
  if (input.disabled) {
    return {
      label: "Unavailable",
      toneClassName: "border-slate-200 bg-slate-100 text-slate-600",
      iconClassName: "",
      Icon: TextCursorInput,
    };
  }
  if (input.imageEnabled) {
    return {
      label: input.screenshotSupported ? "Attachments ready" : "Images ready",
      toneClassName: "border-teal-200 bg-teal-50 text-teal-800",
      iconClassName: "",
      Icon: ImagePlus,
    };
  }
  return {
    label: "Text draft",
    toneClassName: "border-slate-200 bg-slate-50 text-slate-700",
    iconClassName: "",
    Icon: TextCursorInput,
  };
};

export const ComposerStatusBar = ({
  disabled,
  submitting,
  imageEnabled,
  screenshotSupported,
}: ComposerStatusBarProps) => {
  const helpItems = COMPOSER_HELP_ITEMS.filter((item) => imageEnabled || item.label !== "Paste");
  const meta = statusMeta({ disabled, submitting, imageEnabled, screenshotSupported });
  const StatusIcon = meta.Icon;
  const helpContext = useMemo(
    () => helpItems.map((item) => `${item.label}:${item.value}`).join(" | "),
    [helpItems],
  );

  return (
    <div
      className="min-w-0 border-t border-slate-100 px-1.5 py-1 md:px-2"
      data-testid="composer-status-bar"
      data-composer-row="status"
    >
      <div className="grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-center gap-2">
        <Tooltip content="Composer-local state only. Session state stays in the route body.">
          <div
            className={cn(
              "inline-flex h-5.5 min-w-0 items-center gap-1 rounded-full border px-2 text-[10px] leading-none font-medium",
              meta.toneClassName,
            )}
            aria-label={meta.label}
            title={meta.label}
            data-testid="composer-local-status"
          >
            <StatusIcon className={cn("h-3 w-3 shrink-0", meta.iconClassName)} />
            <span className="truncate">{meta.label}</span>
          </div>
        </Tooltip>

        <HelpHint
          ariaLabel="Composer help"
          helpId="composer:shortcuts"
          textContext={`composer-help:${helpContext}`}
          content={
            <div className="space-y-1.5">
              <p className="text-[11px] font-medium text-slate-700">Composer help</p>
              <div className="grid gap-1.5">
                {helpItems.map((item) => (
                  <ShortcutHint key={`${item.label}-${item.value}`} label={item.label} value={item.value} />
                ))}
              </div>
            </div>
          }
          className="h-6 w-6 text-[11px]"
          side="top"
          align="end"
        />
      </div>
    </div>
  );
};

// packages/web-chat-view/src/composer/composer-status-bar.svelte
<script lang="ts">
  import CircleHelp from "@lucide/svelte/icons/circle-help";
  import ImagePlus from "@lucide/svelte/icons/image-plus";
  import LoaderCircle from "@lucide/svelte/icons/loader-circle";
  import TextCursorInput from "@lucide/svelte/icons/text-cursor-input";

  import HelpHint from "../help-hint.svelte";
  import type { ResolvedWebChatComposerCapabilities } from "./composer-contract";

  let {
    disabled,
    submitting,
    capabilities,
    pendingAssetCount,
  }: {
    disabled: boolean;
    submitting: boolean;
    capabilities: ResolvedWebChatComposerCapabilities;
    pendingAssetCount: number;
  } = $props();

  const helpContext = $derived(capabilities.helpItems.map((item) => `${item.label}:${item.value}`).join(" | "));
  const statusMeta = $derived.by(() => {
    if (submitting) {
      return {
        label: "Sending",
        toneClassName: "border-amber-200 bg-amber-50 text-amber-800",
        Icon: LoaderCircle,
        iconClassName: "animate-spin",
      };
    }
    if (disabled) {
      return {
        label: "Unavailable",
        toneClassName: "border-slate-200 bg-slate-100 text-slate-600",
        Icon: TextCursorInput,
        iconClassName: "",
      };
    }
    if (capabilities.attachmentEnabled) {
      return {
        label: pendingAssetCount > 0 ? "Attachments ready" : "Draft + files",
        toneClassName: "border-teal-200 bg-teal-50 text-teal-800",
        Icon: ImagePlus,
        iconClassName: "",
      };
    }
    return {
      label: "Text draft",
      toneClassName: "border-slate-200 bg-slate-50 text-slate-700",
      Icon: TextCursorInput,
      iconClassName: "",
    };
  });
</script>

<div class="composer-status" data-composer-row="status" part="composer-status">
  <div class="composer-status-copy">
    <div class="composer-status-meta {statusMeta.toneClassName}">
      <statusMeta.Icon class={`size-3.5 shrink-0 ${statusMeta.iconClassName}`} />
      <span class="truncate">{statusMeta.label}</span>
    </div>

    {#if capabilities.helpItems.length > 0}
      <div class="composer-status-hints">
        {#each capabilities.helpItems.slice(0, 4) as item (`${item.label}:${item.value}`)}
          <span class="composer-status-hint">
            <span class="composer-status-hint-key">{item.label}</span>
            <span class="truncate">{item.value}</span>
          </span>
        {/each}
      </div>
    {/if}
  </div>

  <HelpHint
    helpId="web-chat-view:composer-shortcuts"
    textContext={`web-chat-view composer: ${helpContext}`}
    ariaLabel="Composer help"
    align="end"
    side="top"
    class="composer-help"
  >
    {#snippet children()}
      <div class="composer-help-trigger" aria-hidden="true">
        <CircleHelp class="size-3.5" />
      </div>
    {/snippet}
  </HelpHint>
</div>

<style>
  .composer-status {
    display: grid;
    grid-template-columns: minmax(0, 1fr) auto;
    align-items: center;
    gap: 0.75rem;
    padding-top: 0.25rem;
  }

  .composer-status-copy {
    display: grid;
    gap: 0.45rem;
    min-width: 0;
  }

  .composer-status-meta {
    display: inline-flex;
    min-width: 0;
    align-items: center;
    gap: 0.4rem;
    border: 1px solid transparent;
    border-radius: 999px;
    padding: 0.25rem 0.6rem;
    font-size: 0.68rem;
    font-weight: 600;
    letter-spacing: 0.02em;
  }

  .composer-status-hints {
    display: flex;
    min-width: 0;
    flex-wrap: wrap;
    gap: 0.35rem;
  }

  .composer-status-hint {
    display: inline-flex;
    min-width: 0;
    align-items: center;
    gap: 0.35rem;
    border-radius: 999px;
    border: 1px solid rgba(226, 232, 240, 0.9);
    background: rgba(255, 255, 255, 0.72);
    padding: 0.18rem 0.5rem;
    font-size: 0.64rem;
    line-height: 1.35;
    color: #64748b;
  }

  .composer-status-hint-key {
    font-weight: 700;
    color: #0f172a;
  }

  .composer-help {
    display: inline-flex;
  }

  .composer-help-trigger {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 1.75rem;
    height: 1.75rem;
    border-radius: 999px;
    border: 1px solid rgba(203, 213, 225, 0.9);
    background: rgba(255, 255, 255, 0.88);
    color: #64748b;
  }

  @container (max-width: 34rem) {
    .composer-status-hints {
      display: none;
    }
  }
  </style>
